repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "9260cbc9c84c06022993bfbcc42fdbf0305c5b8e"
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: name-tests-test
        args: ["--pytest-test-first"]
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: "d9b8a6407e2f46304a8d36b18e4a73d8e0613519"
    hooks:
      - id: black

  - repo: https://github.com/asottile/pyupgrade
    rev: ddb39ad37166dbc938d853cc77606526a0b1622a
    hooks:
      - id: pyupgrade
        args: [--py37-plus, --keep-runtime-typing]

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: 953faa6870f6663ac0121ab4a800f1ce76bca31f
    hooks:
      - id: shellcheck

  - repo: https://github.com/PyCQA/bandit
    rev: fe1361fdcc274850d4099885a802f2c9f28aca08
    hooks:
      - id: bandit
        args: [--exit-zero]
        # ignore all tests, not just tests data
        exclude: ^tests/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.0.1"
    hooks:
      - id: mypy
        exclude: ^(docs/|example-plugin/|tests/fixtures)
        additional_dependencies:
          - "pydantic"

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "6a0ba1854991b693612486cc84a2254de82d071d"
    hooks:
      - id: ruff

  - repo: https://github.com/kynan/nbstripout
    rev: 0.3.9
    hooks:
      - id: nbstripout
